server:
  tomcat:
  uri-encoding: UTF-8
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    active: dev
mybatis:
  type-aliases-package: routine.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: ERROR
    routine: DEBUG


